name: Vercel Production Deployment

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  VERCEL_ORG_ID: jcltSRl27oNddBEszaaDX86J
  VERCEL_PROJECT_ID: prj_7XeYVrgnT7b7nVDjx4FDrbLLsvqx

jobs:
  deploy-production:
    name: Deploy to Vercel (production)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
